# Generated by Django 3.2.24 on 2024-02-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_achievement_alter_answer_text_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 19, 44, 27, 806682), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 19, 44, 27, 808452), verbose_name='Дата и время публикации'),
        ),
    ]
