# Generated by Django 3.2.24 on 2024-02-13 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240211_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 8, 59, 173573), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 8, 59, 175754), verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='ArticleFireWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело статьи')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 8, 59, 174073), verbose_name='Дата и время публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Огневая работа',
                'verbose_name_plural': 'Огневые работы',
            },
        ),
    ]
