# Generated by Django 3.2.24 on 2024-02-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240213_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Иллюстрация статьи',
                'verbose_name_plural': 'Иллюстрации статей',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 14, 27, 32, 749700), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 14, 27, 32, 750620), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 14, 27, 32, 752366), verbose_name='Дата и время публикации'),
        ),
    ]
