# Generated by Django 3.2.24 on 2024-05-21 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240215_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело статьи')),
            ],
            options={
                'verbose_name': 'Обучающая статья',
                'verbose_name_plural': 'Обучающие статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Обучающая статья Уст', 'verbose_name_plural': 'Обучающие статьи Уст'},
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Очередность в обучающем модуле'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 24, 743226), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 24, 744218), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 24, 745218), verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(related_name='students', to='api.Profile', verbose_name='Тесты')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.profile', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tests', models.ManyToManyField(to='api.Test', verbose_name='Тесты')),
                ('theories', models.ManyToManyField(to='api.Theory', verbose_name='Обучающие материалы')),
            ],
        ),
    ]
