# Generated by Django 3.2.24 on 2024-05-22 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240215_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 32, 7, 855342), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 32, 7, 856518), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 32, 7, 858645), verbose_name='Дата и время публикации'),
        ),
    ]
