# Generated by Django 3.2.24 on 2024-05-21 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240521_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 58, 155352), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 58, 155352), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 12, 36, 58, 156352), verbose_name='Дата и время публикации'),
        ),
    ]
