# Generated by Django 3.2.24 on 2024-05-21 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20240521_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': '5 Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='calculatedtest',
            options={'verbose_name': 'Отправленный тест', 'verbose_name_plural': '6 Отправленные тесты'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Обучающий курс', 'verbose_name_plural': '1 Обучающие курсы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос для теста', 'verbose_name_plural': '4 Вопросы для тестов'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Учебный группы', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Проверочный тест', 'verbose_name_plural': '3 Проверочные тесты'},
        ),
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name': 'Обучающая статья', 'verbose_name_plural': '2 Обучающие статьи'},
        ),
        migrations.AddField(
            model_name='theory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Очередность в обучающем модуле'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 5, 3, 171658), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 5, 3, 172658), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tests',
            field=models.ManyToManyField(blank=True, to='api.Test', verbose_name='Тесты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='theories',
            field=models.ManyToManyField(blank=True, to='api.Theory', verbose_name='Обучающие статьи'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='students', to='api.Profile', verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 5, 3, 173659), verbose_name='Дата и время публикации'),
        ),
    ]
