# Generated by Django 3.2.24 on 2024-05-21 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20240521_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 9, 28, 796451), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 9, 28, 797451), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='api.Achievement', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 9, 28, 797451), verbose_name='Дата и время публикации'),
        ),
    ]
