# Generated by Django 3.2.24 on 2024-05-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240522_1432'),
        ('api', '0021_auto_20240521_1409'),
    ]

    operations = [
    ]
