# Generated by Django 3.2.24 on 2024-05-28 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_0011_auto_20240522_1432_0021_auto_20240521_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 14, 6, 38, 153135), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 14, 6, 38, 154079), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 14, 6, 38, 156062), verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='TheoryAndStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile', verbose_name='Студент')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theory', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Статьи и студенты',
                'verbose_name_plural': 'Статьи и студенты',
            },
        ),
    ]
