# Generated by Django 3.2.24 on 2024-06-14 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20240528_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheoryAndStudent',
            new_name='TheoryStudent',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 22, 23, 17, 693770), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 22, 23, 17, 694771), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 22, 23, 17, 698772), verbose_name='Дата и время публикации'),
        ),
    ]
