# Generated by Django 3.2.24 on 2024-06-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20240613_1557'),
        ('api', '0024_auto_20240614_2223'),
    ]

    operations = [
    ]
