# Generated by Django 3.2.24 on 2024-06-20 11:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_merge_0024_auto_20240613_1557_0024_auto_20240614_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedtest',
            name='result',
        ),
        migrations.AddField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 4, 3, 300863), verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='test',
            name='pass_line',
            field=models.FloatField(default=0.6, verbose_name='Проходной процент(от 0 до 1)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 4, 3, 294748), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 4, 3, 295637), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Кол-во очков за ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 4, 3, 298766), verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='TestUserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer', verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленные вопрос и ответ к тесту',
                'verbose_name_plural': 'Отправленные вопрос и ответ к тесту',
            },
        ),
        migrations.AddField(
            model_name='calculatedtest',
            name='test_user_question_answer_list',
            field=models.ManyToManyField(related_name='test_user_question_answer_list', to='api.TestUserQuestionAnswer', verbose_name='Тест пользователь вопрос ответ'),
        ),
    ]
