# Generated by Django 3.2.24 on 2024-06-21 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20240620_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedtest',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Набранное кол-во баллов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 33, 40, 431240), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 33, 40, 432147), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 33, 40, 437798), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 33, 40, 435750), verbose_name='Дата и время публикации'),
        ),
    ]
