# Generated by Django 3.2.24 on 2024-06-21 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20240621_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatedtest',
            old_name='points',
            new_name='user_points',
        ),
        migrations.AddField(
            model_name='calculatedtest',
            name='max_points',
            field=models.IntegerField(default=0, verbose_name='Максимальное кол-во баллов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 35, 55, 514979), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 35, 55, 515947), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 35, 55, 522093), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 35, 55, 519772), verbose_name='Дата и время публикации'),
        ),
    ]
