# Generated by Django 3.2.24 on 2024-06-21 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20240621_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 13, 19, 41, 469292), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 13, 19, 41, 470192), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='max_points',
            field=models.IntegerField(default=0, verbose_name='Максимальное кол-во баллов'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 13, 19, 41, 475591), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='user_points',
            field=models.IntegerField(default=0, verbose_name='Набранное кол-во баллов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 13, 19, 41, 473530), verbose_name='Дата и время публикации'),
        ),
    ]
