# Generated by Django 3.2.24 on 2024-06-21 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20240621_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.IntegerField(default=10, verbose_name='Примерное время на прочтение статьи'),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=10, verbose_name='Примерное время на прохождение теста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 40, 5, 666905), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 40, 5, 668086), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 40, 5, 675024), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 15, 40, 5, 672594), verbose_name='Дата и время публикации'),
        ),
    ]
