# Generated by Django 3.2.24 on 2024-06-23 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20240623_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='points',
            field=models.IntegerField(default=10, verbose_name='Кол-во баллов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 23, 13, 356784), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 23, 13, 357784), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 23, 13, 363786), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 23, 13, 361785), verbose_name='Дата и время публикации'),
        ),
    ]
