# Generated by Django 3.2.24 on 2024-06-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20240623_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 37, 49, 766575), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 37, 49, 767576), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 37, 49, 772578), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10, verbose_name='Кол-во очков за ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 19, 37, 49, 771577), verbose_name='Дата и время публикации'),
        ),
    ]
