# Generated by Django 3.2.24 on 2024-06-26 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20240623_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 11, 20, 49, 329259), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='articlefireworks',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 11, 20, 49, 330183), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='calculatedtest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 11, 20, 49, 336135), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 11, 20, 49, 333982), verbose_name='Дата и время публикации'),
        ),
    ]
